export const UI_TEXT = {
    common: {
        appName: "LMS Assessly",
        loading: "Đang tải...",
        genericError: "Đã xảy ra lỗi. Vui lòng thử lại.",
        save: "Lưu",
        cancel: "Hủy",
        delete: "Xóa",
        close: "Đóng",
        noData: "Không có dữ liệu",
        today: "Hôm nay",
        pdfDocument: "Tài liệu PDF",
        openInNewWindow: "Mở trong cửa sổ mới ↗",
        password: {
            errors: {
                required: "Mật khẩu không được để trống",
                minLength: "Mật khẩu phải có ít nhất 8 ký tự",
                confirmRequired: "Xác nhận mật khẩu không được để trống",
                mismatch: "Mật khẩu xác nhận không khớp",
                weak: "Mật khẩu quá yếu",
            },
            hint: "Tối thiểu 8 ký tự, gồm chữ hoa, chữ thường và số",
        },
        closeModalWarning: {
            title: "Đóng form?",
            description: "Thay đổi chưa lưu sẽ bị mất.",
        },
        errors: {
            recaptchaRequired: "Vui lòng xác nhận reCAPTCHA trước khi đăng nhập",
        },
        icons: {
            userAvatarAlt: "Ảnh đại diện",
            flagAlt: "Cờ",
            badgeAlt: "Huy hiệu",
        },
        symbols: {
            commandK: "⌘K",
            slash: "/",
            colon: ":",
            middleDot: "·",
            ellipsis: "...",
            copyright: "©",
        },
        time: {
            about: "khoảng",
            few: "vài",
        },
        actions: {
            edit: "Sửa",
            copyLink: "Sao chép liên kết",
            delete: "Xóa",
        },
        attendanceStatus: {
            present: "Có mặt",
            late: "Đi muộn",
            absentUnexcused: "Vắng không phép",
            absentExcused: "Vắng có phép",
        },
        pagination: {
            page: "Trang",
            of: "của",
            previous: "Trước",
            next: "Sau",
            totalRecords: "Tổng bản ghi",
            perPage: "/trang",
            clickToChangePage: "Nhấn để đổi trang",
        },
        datePicker: {
            selectDate: "Chọn ngày",
            selectDates: "Chọn ngày",
            today: "Hôm nay",
            yesterday: "Hôm qua",
            thisWeek: "Tuần này",
            lastWeek: "Tuần trước",
            thisMonth: "Tháng này",
            lastMonth: "Tháng trước",
            thisYear: "Năm nay",
            lastYear: "Năm trước",
            allTime: "Tất cả",
            ariaLabel: "Chọn khoảng ngày",
            dash: "–",
            cancel: "Hủy",
            apply: "Áp dụng",
        },
        charts: {
            noData: "Không có dữ liệu biểu đồ",
        },
        richEditor: {
            bold: "In đậm",
            italic: "In nghiêng",
            underline: "Gạch chân",
            strike: "Gạch ngang",
            heading1: "Tiêu đề 1",
            heading2: "Tiêu đề 2",
            heading3: "Tiêu đề 3",
            bulletList: "Danh sách",
            orderedList: "Danh sách số",
            alignLeft: "Căn trái",
            alignCenter: "Căn giữa",
            alignRight: "Căn phải",
            justify: "Căn đều",
            quote: "Trích dẫn",
            codeBlock: "Khối mã",
            horizontalRule: "Đường kẻ",
            link: "Liên kết",
            image: "Hình ảnh",
            table: "Bảng",
            clearFormat: "Xóa định dạng",
            undo: "Hoàn tác",
            redo: "Làm lại",
            toggleHeaderRow: "Hàng tiêu đề",
            toggleHeaderColumn: "Cột tiêu đề",
            toggleHeaderCell: "Ô tiêu đề",
            addColumnBefore: "Thêm cột trước",
            addColumnAfter: "Thêm cột sau",
            deleteColumn: "Xóa cột",
            addRowBefore: "Thêm hàng trước",
            addRowAfter: "Thêm hàng sau",
            deleteRow: "Xóa hàng",
            mergeCells: "Gộp ô",
            splitCells: "Tách ô",
            deleteTable: "Xóa bảng",
        },
    },
    metadata: {
        layout: {
            titleDefault: "LMS Assessly",
            description: "Hệ thống khảo thí và đánh giá năng lực",
            twitterTitle: "LMS Assessly",
            twitterDescription: "Hệ thống khảo thí và đánh giá năng lực",
        },
        home: {
            description: "Chào mừng đến với LMS Assessly",
        },
        login: {
            title: "Đăng nhập",
            description: "Đăng nhập vào LMS Assessly",
        },
    },
    home: {
        title: "LMS Assessly",
        subtitle: "Hệ thống khảo thí và đánh giá năng lực — sẵn sàng để phát triển tính năng mới.",
        loginButton: "Đăng nhập",
        greetingMorning: "Chào buổi sáng,",
        levelShort: "LV",
        totalXp: "Tổng XP",
        classRank: "Hạng lớp",
        streak: "Streak",
        rankPrefix: "#",
        startTour: "Xem hướng dẫn",
        announceTitle: "Thông báo quan trọng",
        announceNewSuffix: "mới",
        viewAllAnnounce: "Xem tất cả →",
        announceEmpty: "Chưa có thông báo mới.",
        pinnedUrgent: "GHIM · KHẨN",
        pinnedCarouselLabel: "Thông báo ghim",
        pinnedDotLabel: "Slide ghim",
        weekTitle: "Lịch học tuần này",
        viewFullSchedule: "Xem lịch đầy đủ →",
        weekEmpty: "Không có lịch · nghỉ",
        characterTitle: "Nhân vật của bạn",
        characterZone: "Khu nhân vật →",
        characterClassPrefix: "Lớp",
        powerLabel: "Sức mạnh tri thức",
        xpWalletLabel: "Ví XP",
        characterCta: "Mặc đồ · nuôi pet · mở rương",
        characterEmptyTitle: "Chọn nhân vật của bạn",
        characterEmptyBody: "Người bạn đồng hành cùng bạn qua từng chặng học",
        characterEmptyCta: "Bắt đầu chọn nhân vật →",
        badgeCabinet: "Tủ huy hiệu",
        leaderboardTitle: "Bảng xếp hạng",
        viewFullBoard: "Xem đầy đủ →",
        xpUnit: "XP",
        meRankBefore: "Bạn đang hạng #",
        meRankAfter: "lớp",
        meGapBefore: "Còn",
        meGapAfter: "XP nữa để vượt hạng trên",
        meRowLabel: "Bạn",
        coursesTitle: "Môn đang học · Dự báo điểm",
        viewPath: "Xem lộ trình →",
        forecastLabel: "Dự báo",
        percentSuffix: "%",
        waveAlt: "Chào",
        flameAlt: "Streak",
        compassAlt: "Hướng dẫn",
        megaphoneAlt: "Thông báo",
        pinAlt: "Ghim",
        calendarAlt: "Ngày",
        clockAlt: "Giờ",
        brainAlt: "Sức mạnh",
        starAlt: "XP",
        jerseyAlt: "Trang phục",
        masksAlt: "Nhân vật",
        trophyAlt: "Xếp hạng",
        rocketAlt: "Thăng hạng",
        medalAlt: "Huy chương",
        nearUnlockTitle: "Sắp mở khóa",
        nearUnlockActionDefault: "Làm ngay →",
        nearUnlockEmptyTitle: "Chưa có huy hiệu nào sắp mở khóa",
        nearUnlockEmptyBody: "Tiếp tục học để tiến gần hơn tới huy hiệu tiếp theo.",
        nearUnlockAllDoneTitle: "Bạn đã mở khóa hết huy hiệu!",
        nearUnlockAllDoneBody: "Đã hoàn thành {earned}/{total} huy hiệu trong tủ — chờ thêm huy hiệu mùa mới nhé.",
        recentAchievementsTitle: "Vừa đạt được",
        recentAchievementsEmptyTitle: "Chưa có hoạt động gần đây",
        recentAchievementsEmptyBody: "Bắt đầu một bài học để ghi nhận thành tích!",
        recentAchievementsEmptyCta: "Đi học ngay →",
    },
    layout: {
        menu: "Menu",
        logout: "Đăng xuất",
        openNavMenu: "Mở menu điều hướng",
        levelPrefix: "Level",
        xpRemainBefore: "Còn",
        xpRemainAfter: "XP lên Level",
        streakUnit: "ngày",
        notificationsTitle: "Thông báo",
        notificationsNewSuffix: "mới",
        viewAllNotifications: "Xem tất cả thông báo →",
        bellEmptyTitle: "Không có thông báo mới",
        bellEmptyBody: "Bạn đã xem hết các thông báo chưa đọc.",
        logoAlt: "RIKKEI Edu",
    },
    navigation: {
        home: "Trang chủ",
        login: "Đăng nhập",
        announcements: "Thông báo",
        studentServices: "Hành chính",
        chatbot: "Rika Support",
        learningPath: "Lộ trình học",
        learningPathShort: "Lộ trình",
        courseRoadmap: "Lộ trình môn học",
        courses: "Môn học",
        results: "Kết quả học tập",
        studyResults: "Thông tin học tập",
        languagePractice: "Luyện ngoại ngữ",
        schedule: "Lịch học",
        leaderboard: "Xếp hạng",
        contests: "Cuộc thi",
        tasks: "Nhiệm vụ",
        avatar: "Nhân vật",
        portfolio: "Portfolio",
        profile: "Hồ sơ",
        groups: {
            overview: "Tổng quan",
            learning: "Học tập",
            achievement: "Thành tích & Game",
        },
    },
    shell: {
        screens: {
            dashboard: {
                title: "Trang chủ học tập",
                subtitle: "Tổng quan tiến độ, XP và năng lực của bạn",
            },
            announcements: {
                title: "Bảng tin",
                subtitle: "Thông báo chung & tin tức từ nhà trường",
            },
            announcementDetail: {
                title: "Chi tiết thông báo",
                subtitle: "Đọc nội dung đầy đủ",
            },
            studentServices: {
                title: "Hành chính sinh viên",
                subtitle: "Dịch vụ hành chính · thủ tục & đơn từ",
            },
            chatbot: {
                title: "Rika Support",
                subtitle: "Hỏi đáp thủ tục hành chính theo tài liệu nhà trường",
            },
            learningPath: {
                title: "Lộ trình học tập",
                subtitle: "Hành trình chinh phục Fullstack Developer",
            },
            courseRoadmap: {
                title: "Lộ trình môn học",
                subtitle: "Toàn bộ môn theo nhóm, tiến độ và định hướng nghề nghiệp",
            },
            courses: {
                title: "Môn học",
                subtitle: "Các môn theo lộ trình Fullstack Developer",
            },
            courseDetail: {
                title: "Chi tiết môn học",
                subtitle: "E-learning: Video · Bài đọc · Trắc nghiệm · BTVN",
            },
            study: {
                title: "Học bài",
                subtitle: "Video → Đọc → Trắc nghiệm → Thực hành",
            },
            results: {
                title: "Kết quả học tập",
                subtitle: "Bảng điểm theo lộ trình & dự báo khả năng qua môn",
            },
            studyResults: {
                title: "Thông tin học tập",
                subtitle: "Chuyên cần, bài tập, e-learning, R-point và điều kiện thi",
            },
            languagePractice: {
                title: "Luyện ngoại ngữ",
                subtitle: "Luyện tiếng Anh & tiếng Nhật mỗi ngày cùng AI",
            },
            schedule: {
                title: "Lịch học",
                subtitle: "Thời khoá biểu tuần & lịch sự kiện học tập",
            },
            leaderboard: {
                title: "Bảng xếp hạng",
                subtitle: "Vinh danh top học viên & vị trí của bạn",
            },
            contests: {
                title: "Cuộc thi & Thành tích",
                subtitle: "Thi đua, nhiệm vụ và thành tựu học tập",
            },
            tasks: {
                title: "Trung tâm nhiệm vụ",
                subtitle: "Việc cần làm hôm nay & cảnh báo sớm",
            },
            avatar: {
                title: "Nhân vật & Thú cưng",
                subtitle: "Đổi trang phục, nuôi pet bằng XP tích luỹ",
            },
            portfolio: {
                title: "E-Portfolio",
                subtitle: "Hồ sơ năng lực & sản phẩm của bạn",
            },
            profile: {
                title: "Hồ sơ cá nhân",
                subtitle: "Thông tin, thành tích & cài đặt tài khoản",
            },
        },
    },
    auth: {
        login: {
            title: "Đăng nhập",
            welcomeBack: "Chào mừng bạn quay lại hành trình học",
            emailLabel: "Email sinh viên",
            passwordLabel: "Mật khẩu",
            submitButton: "Đăng nhập",
            submittingButton: "Đang đăng nhập…",
            logoAlt: "RIKKEI Edu — where dreams come true",
            showPassword: "Hiện mật khẩu",
            hidePassword: "Ẩn mật khẩu",
            showPasswordLabel: "Hiện mật khẩu",
            hidePasswordLabel: "Ẩn mật khẩu",
            errors: {
                emailRequired: "Email không được để trống",
                emailInvalid: "Email không hợp lệ",
                loginFailed: "Email hoặc mật khẩu không đúng. Vui lòng thử lại.",
            },
        },
    },
    errors: {
        title: "Đã xảy ra lỗi",
        somethingWentWrong: "Có lỗi xảy ra. Vui lòng thử lại.",
        retry: "Thử lại",
        forbiddenTitle: "Không có quyền truy cập",
        forbiddenDescription: "Bạn không có quyền truy cập trang này.",
        notFoundTitle: "Không tìm thấy trang",
        notFoundDescription: "Trang bạn tìm không tồn tại.",
        goHome: "Về trang chủ",
    },
    profile: {
        emptyValue: "—",
        specializePrefix: "CN",
        lockedWarning: "Tài khoản đang bị khóa.",
        lockedUntilPrefix: "Đến ",
        infoTitle: "Thông tin cá nhân",
        editTitle: "Chỉnh sửa thông tin",
        changePasswordTitle: "Đổi mật khẩu",
        avatarLabel: "Ảnh đại diện",
        avatarPick: "Chọn ảnh đại diện",
        avatarNoFile: "Chưa chọn file",
        save: "Lưu thay đổi",
        cancel: "Hủy",
        currentPassword: "Mật khẩu hiện tại",
        newPassword: "Mật khẩu mới",
        confirmPassword: "Xác nhận mật khẩu",
        updateSuccess: "Đã cập nhật hồ sơ.",
        updateError: "Không thể cập nhật hồ sơ. Vui lòng thử lại.",
        changePasswordSuccess: "Đã đổi mật khẩu. Vui lòng đăng nhập lại bằng mật khẩu mới.",
        changePasswordError: "Không thể đổi mật khẩu. Vui lòng thử lại.",
        confirmPasswordMismatch: "Mật khẩu xác nhận không khớp.",
        gender: {
            MALE: "Nam",
            FEMALE: "Nữ",
            OTHER: "Khác",
        },
        fields: {
            email: "Email",
            studentCode: "Mã SV",
            fullName: "Họ tên",
            status: "Trạng thái",
            phone: "Số điện thoại",
            dateOfBirth: "Ngày sinh",
            gender: "Giới tính",
            identityCard: "CMND/CCCD",
            address: "Địa chỉ",
            hometown: "Quê quán",
            languages: "Ngoại ngữ",
            facebookAddress: "Facebook",
            systems: "Hệ đào tạo",
            specializes: "Chuyên ngành",
        },
        changePassword: {
            errors: {
                currentPasswordRequired: "Mật khẩu hiện tại không được để trống",
                currentPasswordIncorrect: "Mật khẩu hiện tại không đúng",
                authNotLinked: "Tài khoản chưa được liên kết hệ thống xác thực. Vui lòng liên hệ quản trị viên.",
                newPasswordSameAsOld: "Mật khẩu mới phải khác mật khẩu hiện tại",
                newPasswordLength: "Mật khẩu mới phải từ 6–30 ký tự",
            },
        },
        tourCta: "Xem hướng dẫn",
        classificationPrefix: "Học lực ",
        settingsTitle: "Cài đặt",
        accountTitle: "Tài khoản",
        editInfo: "Chỉnh sửa thông tin cá nhân",
        changePasswordBtn: "Đổi mật khẩu",
        languageBtn: "Ngôn ngữ: Tiếng Việt",
        logout: "Đăng xuất",
        starAlt: "Level",
        graduationAlt: "Học lực",
        compassAlt: "Hướng dẫn",
        settingsAlt: "Cài đặt",
        userAlt: "Tài khoản",
        logoutAlt: "Đăng xuất",
        toastEdit: "✏️ Chỉnh sửa thông tin (stub)",
        toastPassword: "🔒 Đổi mật khẩu (stub)",
        toastLanguage: "🌐 Ngôn ngữ: Tiếng Việt",
    },
    tour: {
        eyebrowPrefix: "HƯỚNG DẪN · ",
        skip: "Bỏ qua",
        prev: "← Trước",
        next: "Tiếp →",
        done: "Hoàn tất 🎉",
        progressSep: " / ",
    },
    dateTimePicker: {
        today: "Hôm nay",
        time: "Thời gian",
        cancel: "Hủy",
        apply: "Áp dụng",
    },
    filter: {
        title: "Bộ lọc",
        condition: "Điều kiện",
        selectField: "Chọn trường",
        selectOperator: "Chọn toán tử",
        enterValue: "Nhập giá trị",
        addCondition: "Thêm điều kiện",
        clearFilters: "Xóa bộ lọc",
        apply: "Áp dụng",
        operators: {
            CONTAINS: "Chứa",
            NOT_CONTAINS: "Không chứa",
            EQUALS: "Bằng",
            NOT_EQUALS: "Khác",
            STARTS_WITH: "Bắt đầu bằng",
            ENDS_WITH: "Kết thúc bằng",
            IS_EMPTY: "Rỗng",
            IS_NOT_EMPTY: "Không rỗng",
            GREATER_THAN: "Lớn hơn",
            GREATER_THAN_OR_EQUAL: "Lớn hơn hoặc bằng",
            LESS_THAN: "Nhỏ hơn",
            LESS_THAN_OR_EQUAL: "Nhỏ hơn hoặc bằng",
            IN: "Thuộc",
            NOT_IN: "Không thuộc",
        },
        boolean: {
            true: "Đúng",
            false: "Sai",
        },
    },
    courseRoadmap: {
        title: "Lộ trình môn học",
        subtitle: "Toàn bộ môn theo nhóm, tiến độ và định hướng nghề nghiệp",
        overallProgress: "{completed}/{total} môn",
        systemSelectorLabel: "Hệ đào tạo",
        careerLensLabel: "Định hướng nghề",
        careerLensAll: "Tất cả",
        careerProgress: "Để trở thành {career}: {completed}/{total} môn hoàn thành",
        uncategorizedTitle: "Khác",
        statusDone: "Hoàn thành",
        statusInProgress: "Đang học",
        statusLocked: "Chưa mở",
        emptyTitle: "Chưa có lộ trình học",
        emptyDesc: "Bạn chưa được xếp môn vào lộ trình. Vui lòng liên hệ nhà trường nếu cần hỗ trợ.",
        errorTitle: "Không tải được lộ trình môn học",
        retry: "Thử lại",
        hoursSuffix: "giờ",
        careerSectionTitle: "Định hướng nghề nghiệp",
        careerSectionSubtitle: "Để đạt mỗi nghề, hoàn thành các môn sau",
        pathsSectionTitle: "Roadmap",
        pathsSectionSubtitle: "Chọn nhóm môn để xem lộ trình theo thứ tự học",
        detailTitle: "Chi tiết môn học",
        enterCourse: "Vào học",
        lockedNote: "Hoàn thành môn trước để mở khóa",
        close: "Đóng",
        stationAria: "Xem chi tiết môn {code}",
    },
    learningPath: {
        heroLabel: "Lộ trình · Fullstack Web Developer",
        heroTitle: "Hành trình chinh phục 6 chặng",
        heroProgressSuffix: "môn hoàn thành",
        skillSectionTitle: "Kỹ năng & nghề nghiệp mở khóa",
        skillSectionSubtitle: "Mỗi môn hoàn thành mở khóa kỹ năng và mở ra vị trí công việc phù hợp",
        skillUnlockedLabel: "Kỹ năng mở khóa",
        jobMatchLabel: "Phù hợp với công việc",
        subjectPrefix: "Môn",
        unlockStatus: {
            done: "Đã mở khóa",
            current: "Đang mở khóa",
            locked: "Chưa mở khóa",
        },
        skillMarkDone: "✓",
        skillMarkCurrent: "•",
        lockedSkillToast: "🔒 Hoàn thành môn trước để mở khóa kỹ năng này",
        sectionIconAlt: "Lộ trình",
        brainAlt: "Kỹ năng",
        briefcaseAlt: "Công việc",
        lockAlt: "Khóa",

        careerSectionTitle: "AI Gợi ý nghề nghiệp",
        careerSectionSubtitle: "Dựa trên 2 môn đã hoàn thành + 1 môn đang học · đối chiếu JD thị trường",
        careerBestBadge: "Phù hợp nhất hiện tại",
        careerBestSuffix: "phù hợp",
        careerSalaryPrefix: "Lương tham khảo",
        careerLevelSalarySep: " · ",
        skillsHaveLabel: "Kỹ năng đã có",
        skillsMissingLabel: "Cần bổ sung",
        skillMissingPrefix: "+",
        goalBadge: "MỤC TIÊU LỘ TRÌNH",
        matchSuffix: "%",
        mapAlt: "Lộ trình",
        robotAlt: "AI",
        starAlt: "Phù hợp",
        targetAlt: "Mục tiêu",
        checkAlt: "Đã có",
    },
    courses: {
        searchPlaceholder: "Tìm môn học, giảng viên…",
        systemLabel: "Hệ học",
        semesterLearnPrefix: "Học",
        semesterBadgePrefix: "Kì",
        lessonsCountSuffix: "bài học",
        semesterCourseCountSuffix: "môn",
        semesterProgressDoneSuffix: "hoàn thành",
        ctaReview: "Ôn tập →",
        ctaEnter: "Vào học →",
        ctaLocked: "🔒 Khóa",
        emptyTitle: "Không tìm thấy môn học",
        emptyBody: "Thử từ khóa khác hoặc kiểm tra chính tả nhé.",
        searchAlt: "Tìm kiếm",
        lockedToast: "🔒 Hoàn thành môn trước để mở khóa",
        status: {
            done: "Hoàn thành",
            current: "Đang học",
            locked: "Đã khóa",
        },
    },
    courseDetail: {
        backButton: "Tất cả môn học",
        expandCurriculum: "Mở danh sách buổi",
        collapseCurriculum: "Thu gọn danh sách",
        mapTitlePrefix: "Bản đồ hành trình ·",
        mapLegendHintBefore: "Cột mốc",
        mapLegendHintSession: "Session",
        mapLegendHintMid: "(hình vuông) · các",
        mapLegendHintLesson: "bài học",
        mapLegendHintAfter: "(hình tròn) nằm giữa hai mốc",
        guideButton: "Hướng dẫn",
        mapTour: {
            eyebrowPrefix: "HƯỚNG DẪN BẢN ĐỒ · ",
            done: "Bắt đầu học 🎉",
        },
        openChestTitle: "Mở rương báu",
        legendSession: "Session",
        legendSessionSuffix: "(cột mốc)",
        legendLesson: "Bài học",
        legendLessonSuffix: "(node tròn)",
        legendDone: "Đã học",
        legendCurrent: "Đang học",
        legendLocked: "Chưa mở",
        mapPanelHint: "Bấm một chặng trên bản đồ để xem",
        mapPanelStagePrefix: "Chặng",
        mapPanelGoEnter: "Vào học chặng này →",
        mapPanelGoReview: "Ôn tập chặng này →",
        mapPanelGoLocked: "🔒 Chưa mở khóa",
        mapPanelGoEmpty: "Chưa có bài học",
        mapPanelBtvn: "Bài tập về nhà",
        mapPanelChip: {
            done: "Đã hoàn thành",
            current: "Đang học",
            locked: "Chưa mở",
        },
        mapPanelLessonStatus: {
            done: "Đã học",
            current: "Đang học",
            locked: "Sẽ học",
        },
        sessionPrefix: "Session",
        /** Short glyph stacked under the flag icon on the map session badge, EP `S{n}`. */
        sessionShort: "S",
        sessionMetaLessonWord: "lesson",
        sessionMetaDoneSuffix: "hoàn thành",
        sessionMetaSuffix: "bài học",
        sessionCountSuffix: "session",
        clearedSuffix: "chặng đã qua",
        chestWaitingSuffix: "rương chờ mở",
        itemLabels: {
            lesson: "Bài học",
            btvn: "Bài tập về nhà (BTVN)",
            practice: "Bài thực hành",
            flash: "Flashcard",
            help: "Hỏi đáp / AI",
            mind: "Mindmap",
            quiz: "Quiz",
            resources: "Video Record & Tài liệu",
        },
        sessionPhases: {
            before: "Trước buổi học",
            during: "Trong buổi học",
            after: "Sau buổi học",
        },
        quizComingSoon: {
            title: "Quiz",
            body: "Coming soon",
        },
        resources: {
            loading: "Đang tải tài nguyên học tập...",
            loadError: "Không tải được tài nguyên. Vui lòng thử lại.",
            noClass: "Không tìm thấy lớp học cho môn này.",
            empty: "Chưa có tài nguyên nào cho buổi học này.",
            emptyHint: "Giảng viên hoặc giáo vụ sẽ đính kèm video record và tài liệu sau buổi học.",
            notAttached: "Chưa đính kèm",
            noVideos: "Chưa có video nào",
            noDocuments: "Chưa có tài liệu nào",
            copied: "Đã sao chép",
            open: "Mở",
            bannerTitle: "Xem lại Video Record & Tài liệu Bài giảng",
            bannerBody: "Truy cập lại bài giảng đã ghi hình và tài liệu đính kèm cho buổi học này.",
            videoTitle: "Video Record buổi học",
            videoDesc: "Xem lại buổi học trên YouTube, Zoom, Google Drive hoặc Vimeo.",
            documentTitle: "Tài liệu bổ sung",
            documentDesc: "Mở tài liệu tham khảo do giảng viên đính kèm.",
            openVideo: "Xem Video",
            openDocument: "Mở tài liệu",
            openVideoShort: "Xem",
            openDocumentShort: "Mở",
            videosSectionTitle: "Video Record",
            documentsSectionTitle: "Tài liệu",
            itemCount: (count: number) => `${count} mục`,
            supplementaryBadge: "Bổ sung",
            extraVideosTitle: "Video bổ sung",
            extraVideoPrefix: "Video bổ sung",
        },
        lessonPrefix: "Bài",
        lockedToast: "🔒 Hoàn thành bài trước để mở khóa",
        emptyChapterToast: "Chặng này chưa có bài học",
        emptyChapterAccordionHint: "Chưa có bài học trong chặng này.",
        emptyChapterAccordionPracticeHint: "Bạn vẫn có thể nộp bài thực hành bên dưới.",
        noEnterableLessonToast: "Chưa có bài học nào để bắt đầu. Hoàn thành chặng trước hoặc liên hệ giảng viên nếu chặng đầu không có nội dung.",
        noSessionYet: "Môn học này chưa mở khóa. Hãy hoàn thành các môn trước để mở nội dung.",
        lessonPreview: {
            stepsHint: "{count} chặng học tương tác · hoàn thành nhận",
            xpBonus: "+{xp} XP",
            enterStudyCta: "Bắt đầu học →",
        },
        hw: {
            title: "Bài tập về nhà",
            totalSuffix: "bài",
            listBackLabel: "Danh sách BTVN",
            submittedStatus: "Đã nộp",
            pendingStatus: "Chưa nộp",
            submittedCountSeparator: "đã nộp",
            sessionSubmittedLabel: "Đã nộp bài",
            sessionNotSubmittedLabel: "Chưa nộp bài",
            progressFraction: "{submitted}/{total}",
            orderBtnAria: "Bốc thêm bài tập",
            requirementsTitle: "Đề bài / Yêu cầu",
            gradingCriteriaTitle: "Tiêu chí chấm",
            tutorialTitle: "Hướng dẫn",
            sampleLinkTitle: "Mẫu tham khảo",
            deadlinePrefix: "Thời gian ước tính:",
            expectedTimeLabel: "≈ {minutes} phút",
            noTimeLimit: "Không giới hạn",
            defaultTitlePrefix: "Bài tập",
            noRequirementsFallback: "Xem mô tả trên LMS hoặc liên hệ giảng viên để biết yêu cầu chi tiết.",
            emptyList: "Chờ giảng viên giao bài tập về nhà cho bạn nhé!",
            emptyUnavailable: "Chưa có bài tập khả dụng",
            loading: "Đang tải bài tập...",
            orderBtn: "Bốc thêm bài tập",
            orderingBtn: "Đang bốc bài...",
            orderExhaustedBtn: "Đã nhận tất cả bài tập của buổi",
            orderUnavailableBtn: "Chưa có bài tập khả dụng",
            orderSuccessToast: "Bốc thành công bài tập {title} (Độ khó: {difficulty})!",
            orderExhaustedToast: "Bạn đã nhận tất cả bài tập của buổi này.",
            orderUnavailableToast: "Chưa có bài tập khả dụng cho buổi học này.",
            orderNotEnrolledToast: "Bạn chưa được xếp vào lớp học. Vui lòng liên hệ Giáo vụ.",
            orderError: "Không bốc được bài tập. Hãy thử lại.",
            difficulty: {
                EXCELLENT: "Xuất sắc",
                GOOD: "Giỏi",
                FAIR: "Khá",
                MEDIUM: "Trung bình",
                EASY: "Dễ",
            },
            submissionsTitle: "Lịch sử nộp bài",
            submissionsEmpty: "Chưa có lần nộp nào.",
            submissionsLoading: "Đang tải lịch sử nộp...",
            submissionAttemptPrefix: "Lần",
            submissionAiStatus: {
                PENDING: "Chờ AI",
                RUNNING: "AI đang chấm",
                COMPLETED: "AI đã chấm",
                FAILED: "AI lỗi",
                SKIPPED: "Hết lượt AI — chờ GV",
                UNKNOWN: "Không rõ",
            },
            submitSuccess: "Đã nộp bài — hệ thống đang chờ AI chấm.",
            submitError: "Không nộp được bài. Hãy thử lại.",
            completionStatus: {
                PENDING_AI: "Đang chờ AI chấm",
                PENDING_TEACHER: "Chờ giảng viên chấm",
                COMPLETED: "Hoàn thành",
                NOT_COMPLETED: "Chưa đạt — có thể nộp lại",
            },
            aiFeedbackTitle: "Nhận xét AI",
            aiScoreLabel: "Điểm AI",
            steps: [
                { num: "1", label: "Làm bài trên máy" },
                { num: "2", label: "Push lên GitHub (public)" },
                { num: "3", label: "Dán link nộp bên dưới" },
            ],
            linkLabel: "Link GitHub để nộp bài",
            linkRequiredMark: "*",
            linkPlaceholder: "https://github.com/tài-khoản/tên-repo",
            linkHint: "Dán link repository hoặc Pull Request. Nhớ để repo ở chế độ public để giảng viên xem & chấm được.",
            invalidLinkError: "Link chưa hợp lệ — hãy dán đường dẫn dạng github.com/tài-khoản/tên-repo.",
            submitBtn: "Nộp bài tập",
            submittedTitle: "Đã nộp bài thành công",
            submittedAtPrefix: "Nộp lúc",
            savedLinkLabel: "Link đã nộp",
            editBtn: "Nộp lại / Sửa link",
        },
        devPass: {
            passSession: "Pass session",
            passLesson: "Pass",
            chipTitle: "Chỉ hiện khi chạy local dev",
        },
        practice: {
            defaultTitle: "Tổng kết",
            title: "Bài thực hành",
            totalSuffix: "bài",
            listBackLabel: "Danh sách thực hành",
            submittedStatus: "Đã nộp",
            pendingStatus: "Chưa nộp",
            sessionSubmittedLabel: "Đã nộp hết bài thực hành",
            sessionNotSubmittedLabel: "Chưa nộp đủ bài thực hành",
            requirementsTitle: "Đề bài / Yêu cầu",
            emptyList: "Buổi này chưa có bài thực hành được cấu hình.",
            noRequirementsFallback: "Xem mô tả trên LMS hoặc liên hệ giảng viên để biết yêu cầu chi tiết.",
            submitSuccess: "Đã nộp bài thực hành!",
            submitError: "Không nộp được bài. Hãy thử lại.",
            steps: [
                { num: "1", label: "Làm bài trên máy" },
                { num: "2", label: "Push lên GitHub (public)" },
                { num: "3", label: "Dán link nộp bên dưới" },
            ],
            linkLabel: "Link GitHub để nộp bài",
            linkRequiredMark: "*",
            linkPlaceholder: "https://github.com/tài-khoản/tên-repo",
            linkHint: "Dán link repository hoặc Pull Request. Repo public để giảng viên xem được.",
            invalidLinkError: "Link chưa hợp lệ — hãy dán đường dẫn dạng github.com/tài-khoản/tên-repo.",
            submitBtn: "Nộp bài thực hành",
            submittedTitle: "Đã nộp bài thành công",
            submittedAtPrefix: "Nộp lúc",
            savedLinkLabel: "Link đã nộp",
            editBtn: "Nộp lại / Sửa link",
            lockedToast: "Hoàn thành hết bài học trong buổi trước khi nộp thực hành nhé.",
        },
        flash: {
            cardLabel: "Thẻ",
            positionSeparator: "·",
            hintDrag: "Kéo chuột để lật thẻ",
            frontLabel: "Câu hỏi",
            backLabel: "Trả lời",
            flipBtn: "Lật thẻ",
            flipHint: "↔ Kéo sang ngang để lật",
            pronunciationLabel: "Phát âm",
            exampleLabel: "Ví dụ",
            known: "Đã thuộc",
            markKnown: "Đánh dấu đã thuộc",
            markUnknown: "Bỏ đánh dấu",
            progressPrefix: "Đã thuộc",
            progressSeparator: "/",
            loading: "Đang tải flashcard...",
            empty: "Bộ flashcard này chưa có thẻ nào.",
            saveError: "Không lưu được tiến độ, thử lại nhé.",
        },
        help: {
            title: "Trợ lý học tập AI",
            subtitlePrefix: "Hỏi đáp trong phạm vi tài nguyên môn",
            inputPlaceholder: "Nhập câu hỏi của bạn...",
            actions: ["Giải thích lại dễ hiểu hơn", "Tóm tắt bài học", "Sinh câu hỏi luyện tập", "Gợi ý sửa lỗi code"],
        },
        mind: {
            titlePrefix: "Mindmap ·",
            subtitle: "Bấm + thêm nhánh · click vào chữ để sửa · kéo viền để di chuyển · lưu góc phải canvas",
            saveBtn: "Lưu Mindmap",
            saveBtnTitle: "Lưu mindmap",
            expandBtnTitle: "Phóng to mindmap",
            expandModalClose: "Thu nhỏ",
            expandedPlaceholder: "Đang chỉnh sửa ở chế độ phóng to",
            addBranchBtn: "Thêm nhánh",
            removeBranchBtn: "Xóa nhánh",
            editBranchBtn: "Sửa nhánh",
            submittedBadge: "Đã nộp",
            teacherNoteLabel: "Nhận xét giảng viên",
            saveSuccess: "Đã lưu mindmap",
            saveError: "Không thể lưu mindmap. Thử lại sau.",
            minNodesHint: "Thêm ít nhất 2 nhánh trước khi lưu",
            lockedToast: "Hoàn thành các bài học trong chặng trước khi vẽ mindmap",
            loading: "Đang tải mindmap...",
            newNodeText: "Nhánh mới",
        },
    },
    study: {
        exitBtn: "Thoát",
        guideButton: "Hướng dẫn cách học",
        tour: {
            eyebrowPrefix: "Hướng dẫn học · ",
            done: "Bắt đầu học 🎉",
        },
        lessonTitlePrefix: "Bài",
        lessonTitleSeparator: ":",
        xpUnit: "XP",
        stepLabels: {
            video: "Video",
            read: "Bài đọc",
            quiz: "Trắc nghiệm",
            practice: "Thực hành",
        },
        /** Mascot speech-bubble copy per active step, ported from EP `mascotByStep`. */
        mascotByStep: {
            video: "Cùng xem video nào! Xong chặng này +30 XP 🎬",
            read: "Đọc kỹ phần này nhé, toàn kiến thức vàng! 📚",
            quiz: "Thử tài xem nào — trả lời đúng để ghi điểm! 🎯",
            practice: "Tự tay code thử, học đi đôi với hành! 💪",
        },
        readTitlePrefix: "Bài đọc:",
        rememberLabel: "Ghi nhớ:",
        practiceTitlePrefix: "Thực hành:",
        practiceSubtitle: "Làm theo từng bước · có input/output mẫu",
        practicePromptTitle: "Đề bài",
        practiceRunBtn: "Chạy & kiểm tra",
        quizBadge: "Câu hỏi · +10 XP nếu đúng",
        progressLabel: "Tiến độ bài học",
        completeStepLabel: "Hoàn thành chặng →",
        completeLessonLabel: "Hoàn thành bài học 🎉",
        stepCompleteToast: "+30 XP · Tuyệt vời!",
        nextLessonToast: "➡️ Bài tiếp theo!",
        xpFlyLabel: "+30 XP",
        quizSubmitBtn: "Nộp đáp án",
        quizRetryBtn: "Làm lại",
        quizCorrectResult: "🎉 Chính xác! +10 XP",
        quizWrongResult: "Chưa đúng — đáp án đúng đã được đánh dấu ở trên.",
        quizSubmitNotPassedToast: "Chưa đạt 100%. Hãy sửa đáp án và nộp lại nhé.",
        quizSubmitPassedToast: "Đạt 100%! Bấm Hoàn thành bài học để kết thúc nhé.",
        quizAnswerAllRequiredToast: "Hãy chọn đáp án cho tất cả câu hỏi trước khi nộp bài.",
        quizTimedOutToast: "Hết giờ! Hệ thống đã nộp bài. Bạn chưa đạt điểm pass — hãy làm lại nhé.",
        quizCompleteRequiredToast: "Cần nộp bài và đạt 100% trước khi hoàn thành bài học nhé",
        videoQuestionSubmitMulti: "Xác nhận đáp án",
        unlockLessonError: "Phải hoàn thành các bài trước đó",
        unlockSessionError: "Buổi học chưa được mở khóa",
        lessonLoadError: "Không thể mở bài học",
        readingSubmitBtn: "Nộp bài đọc",
        readingTextAnswerPlaceholder: "Nhập câu trả lời của bạn...",
        readingAnswerRequiredToast: "Hãy trả lời hết câu hỏi bài đọc trước khi nộp",
        readingCompleteRequiredToast: "Hãy nộp bài đọc trước khi hoàn thành chặng nhé",
        readingSubmitPassedToast: "Đã nộp bài đọc! Bấm Hoàn thành chặng để tiếp tục nhé.",
        readingQuestionsTitle: "Câu hỏi kiểm tra bài đọc",
        noVideo: "Chưa có video cho bài học này.",
        quizPassHint: "Cần đạt tối thiểu {threshold}% để hoàn thành bài kiểm tra",
        lockedStepToast: "🔒 Hoàn thành chặng trước đã nhé",
        videoWatchRequiredToast: "Hãy xem ít nhất 80% video trước khi hoàn thành chặng nhé 🎬",
        videoQuestionsRequiredToast: "Trả lời hết câu hỏi trong video trước khi tiếp tục nhé",
        videoQuestionWrongToast: "Chưa đúng — hãy chọn lại đáp án nhé.",
        videoQuestionWrongHint: "Chưa đúng. Hãy chọn lại đáp án và nộp lại.",
        celebrate: {
            title: "Qua màn!",
            bodyPrefix: "Bạn đã chinh phục",
            xpLabel: "XP nhận được",
            stepsLabel: "Step hoàn thành",
            backToMapBtn: "Về bản đồ",
            nextLessonBtn: "Bài tiếp theo →",
            openChestBtn: "Mở rương báu",
            finishBtn: "Hoàn tất →",
        },
    },
    leaderboard: {
        podiumEyebrow: "Bảng vinh danh · Lớp K18-CNTT",
        podiumTitle: "Top học viên xuất sắc",
        trophyAlt: "Cúp",
        xpUnit: "XP",
        searchPlaceholder: "Tìm bạn học theo tên hoặc lớp…",
        searchAlt: "Tìm bạn học",
        emptyTitle: "Không tìm thấy bạn học nào",
        flameAlt: "Streak",
        searchEmptyAlt: "Không có kết quả",
        scope: {
            he: "Toàn Hệ",
            khoa: "Khóa K18",
            lop: "Lớp CNTT-01",
            mon: "Môn React",
        },
    },
    tasks: {
        tabToday: "Nhiệm vụ hôm nay",
        tabAlert: "Cảnh báo",
        heroEyebrow: "Nhiệm vụ hôm nay",
        heroTitle: "Hoàn thành để nhận XP!",
        heroBody: "Mỗi nhiệm vụ là một bước tiến — gom XP để lên cấp, nuôi pet và mở rương.",
        doneLabel: "xong",
        xpTodaySuffix: "XP hôm nay",
        xpSlash: "/",
        allDoneTitle: "Tuyệt vời! Hoàn thành hết nhiệm vụ hôm nay",
        allDoneBodyBefore: "Bạn đã gom trọn",
        allDoneBodyAfter: "XP — quay lại vào ngày mai nhé!",
        xpPrefix: "+",
        xpDonePrefix: "✓ +",
        xpUnit: "XP",
        toastXpPrefix: "+",
        toastXpMid: "XP ·",
        clockAlt: "Hạn",
        starAlt: "XP",
        rocketAlt: "Rocket",
        partyAlt: "Hoàn thành",
        checkAlt: "Hoàn thành nhiệm vụ",
    },
    results: {
        gpaLabel: "GPA tích lũy",
        gpaScale: "Hệ điểm 4.0",
        gpaDenom: "/ 4.0",
        avg100Label: "Điểm TB hệ 100",
        avg100Suffix: "/ 100",
        classificationLabel: "Xếp loại học lực",
        creditsLabel: "Tín chỉ đã đạt",
        creditsSuffix: "TC",
        transcriptTitle: "Bảng điểm chi tiết",
        transcriptHint: "Điểm thành phần hệ 100 · QT 10% · GK 30% · CK 60% → quy đổi GPA hệ 4.0",
        updatedPrefix: "Cập nhật",
        colSubject: "Môn học",
        colCredit: "TC",
        colQt: "QT",
        colGk: "GK",
        colCk: "CK",
        colTotal: "Hệ 100",
        colLetter: "Điểm chữ",
        colGpa: "GPA",
        gradeScaleLabel: "Thang quy đổi",
        dash: "—",
        statusCurrent: "Đang học",
        statusLocked: "Chưa học",
        tabInfo: "Thông tin học tập",
        tabCriteria: "Kết quả học tập",
        courseLabel: "Môn học",
        coursePlaceholder: "Chọn môn",
        criteriaEmptyCourse: "Chọn môn để xem chuyên cần, bài tập, e-learning, R-point và điều kiện thi.",
        criteriaEmptyEnroll: "Bạn chưa được xếp lớp môn nào.",
        attendanceTitle: "Chuyên cần",
        attendanceHint: "Tỉ lệ có mặt / tổng buổi dự kiến",
        attendanceAbsent: "Buổi nghỉ",
        homeworkTitle: "Bài tập về nhà",
        homeworkHint: "Buổi đã hoàn thành / buổi có bài tập",
        elearningTitle: "E-learning",
        elearningHint: "Chuẩn bị đúng hạn trước buổi lên lớp",
        elearningLate: "Buổi muộn",
        rpointTitle: "R-point",
        rpointHint: "Điểm rèn luyện đã chốt hoặc mới nhất",
        rpointLocked: "Đã chốt",
        rpointOpen: "Chưa chốt",
        rpointDetailCta: "Xem chi tiết",
        rpointModalTitle: "Chi tiết R-point",
        rpointModalSubtitle: "Bảng điểm rèn luyện theo từng thành phần",
        rpointTotalLabel: "Tổng điểm",
        rpointSectionScores: "Điểm thành phần",
        rpointSectionBonus: "Điểm thưởng",
        rpointSectionSnapshot: "Snapshot đầu vào",
        rpointAttendanceScore: "Chuyên cần",
        rpointAssignmentScore: "Bài tập",
        rpointPreparationScore: "Chuẩn bị bài",
        rpointComplianceScore: "Tuân thủ",
        rpointBaseScore: "Điểm cơ bản",
        rpointLearningBonus: "Thưởng học tập",
        rpointClassOfficerBonus: "Thưởng cán sự",
        rpointManualBonus: "Thưởng thủ công",
        rpointBonusTotal: "Tổng thưởng",
        rpointAbsenceRate: "Tỉ lệ nghỉ",
        rpointSubmissionRate: "Tỉ lệ nộp bài",
        rpointElearningRate: "Tỉ lệ e-learning",
        rpointLateCount: "Số lần nộp muộn",
        rpointViolationCount: "Số lần vi phạm",
        rpointRecordedDate: "Ngày ghi nhận",
        rpointEmptyDetail: "Chưa có bảng điểm R-point cho môn này.",
        examTitle: "Điều kiện thi",
        examHint: "Đủ điều kiện khi đạt cả 4 tiêu chí: R-point, chuyên cần, bài tập và e-learning",
        examPass: "Đủ điều kiện thi",
        examFail: "Chưa đủ điều kiện thi",
        examThreshold: "Ngưỡng R-point",
        examNeedPrefix: "Còn",
        examNeedSuffix: "điểm R-point nữa để đạt ngưỡng điểm rèn luyện",
        examNeedFailPrefix: "Chưa đạt",
        examMetBody: "Bạn đã đạt cả 4 tiêu chí, đủ điều kiện dự thi.",
        examCriterionRpoint: "R-point",
        examCriterionAttendance: "chuyên cần",
        examCriterionHomework: "bài tập",
        examCriterionElearning: "e-learning",
        examCurrent: "R-point hiện tại",
        attendedLabel: "Có mặt",
        homeworkDoneLabel: "Hoàn thành",
        elearningOnTimeLabel: "Đúng hạn",
        rateSuffix: "%",
        forecastTitle: "Dự báo qua môn · ReactJS",
        forecastProbLabel: "khả năng",
        forecastProbSuffix: "%",
        forecastGoodTitle: "Khả năng qua môn cao",
        forecastGoodBody: "Dựa trên chuyên cần, bài tập, e-learning và RPOINT theo rubric môn học.",
        aiTipsTitle: "Gợi ý bổ sung kiến thức từ AI",
        aiTipBullet: "→",
        clipboardAlt: "Bảng điểm",
        examAvatarAlt: "Điều kiện thi",
        criteriaWaveAlt: "Họa tiết",
        robotAlt: "AI",
    },
    announcements: {
        catAll: "Tất cả",
        pinnedBadge: "Ghim · Giáo vụ",
        pinnedPrefix: "Ghim",
        pinnedCarouselLabel: "Thông báo ghim",
        pinnedDotLabel: "Slide ghim",
        viewsSuffix: "lượt xem",
        searchPlaceholder: "Tìm thông báo…",
        searchAlt: "Tìm thông báo",
        emptyTitle: "Không có thông báo phù hợp",
        emptyBody: "Thử từ khóa khác hoặc chọn lại danh mục.",
        backButton: "Tất cả thông báo",
        markRead: "Đã đọc & xác nhận",
        save: "Lưu lại",
        share: "Chia sẻ",
        pinAlt: "Ghim",
        calendarAlt: "Ngày",
        eyeAlt: "Lượt xem",
        pencilAlt: "Tác giả",
        clockAlt: "Thời gian đọc",
        inboxAlt: "Trống",
        markReadToast: "Bạn đã xác nhận thông báo",
        newRealtimeToast: "Bạn nhận được thông báo mới",
        saveToast: "Đã lưu thông báo",
        shareToast: "Đã sao chép liên kết chia sẻ",
        notFoundTitle: "Không tìm thấy thông báo",
        notFoundBody: "Thông báo này không tồn tại hoặc đã bị gỡ.",
    },
    game: {
        heroEyebrow: "Nhân vật của bạn",
        heroNoChar: "Chưa chọn",
        heroNoCls: "—",
        xpWalletLabel: "Ví XP",
        tabChar: "Nhân vật",
        tabPet: "Thú cưng",
        tabShop: "Cửa hàng XP",
        classPrefix: "Lớp",
        powerLabel: "Sức mạnh tri thức",
        equipSlotsLabel: "Ô trang bị · 6 slot",
        changeChar: "Đổi nhân vật",
        outfitSection: "Trang phục · chạm để mặc",
        gearSection: "Đồ đạc & trang sức · chạm để đeo",
        chestHintBefore: "Mở",
        chestHintBold: "rương báu",
        chestHintAfter: "khi qua chương hoặc mua ở Cửa hàng để sưu tầm đồ đạc.",
        btnEquipped: "✓ Đang dùng",
        btnWear: "Mặc",
        btnOwned: "Đã sở hữu",
        btnPricePrefix: "⭐ ",
        gearWorn: "✓ Đang đeo",
        gearTap: "Chạm để đeo",
        gearLocked: "Chưa có",
        petFullLabel: "Độ no",
        petXpLabel: "Kinh nghiệm",
        feedBtn: "Cho ăn · 50 XP",
        feedHint: "Cho ăn để pet lớn nhanh & mở kỹ năng cổ vũ học tập",
        adoptTitle: "Nhận nuôi một thú cưng",
        adoptBody: "Pet đồng hành cùng bạn, ăn XP để lớn và cổ vũ mỗi khi bạn học.",
        adoptCta: "Nhận nuôi (miễn phí)",
        shopIntroBefore: "Dùng",
        shopIntroBold: "XP tích luỹ",
        shopIntroAfter: "đổi trang phục, thức ăn cho pet và vật phẩm hỗ trợ học tập.",
        stageMature: "🌟 Trưởng thành",
        stageGrowing: "🌿 Đang lớn",
        stageBaby: "🥚 Sơ sinh",
        modalEyebrow: "Bắt đầu hành trình",
        modalTitle: "Chọn nhân vật của bạn",
        modalBody: "Người bạn đồng hành sẽ cùng bạn chinh phục từng chặng học",
        modalClose: "Đóng",
        chestEyebrow: "Qua chương · Rương báu!",
        chestPowerPrefix: "+",
        chestPowerSuffix: " sức mạnh tri thức",
        chestClaim: "Nhận phần thưởng",
        courseCompleteEyebrow: "Hoàn thành khoá học",
        courseCompleteCertTitle: "Chứng chỉ hoàn thành",
        courseCompleteCertBodyBefore: "đã hoàn tất",
        courseCompleteCertBodyMid: "chặng học · cấp ngày",
        courseCompleteBadgePrefix: "Huy hiệu: Bậc thầy",
        courseCompleteXpLabel: "Tổng XP khoá học",
        courseCompleteChaptersLabel: "Chặng chinh phục",
        courseCompleteCta: "Nhận huy hiệu & tiếp tục",
        feedbackEyebrow: "Đánh giá môn học",
        feedbackIntro: "Chia sẻ cảm nhận của bạn để giúp cải thiện khoá học",
        feedbackRatingPrompt: "Bạn thấy môn học này thế nào?",
        feedbackDifficultyPrompt: "Độ khó của môn học",
        feedbackTagsPrompt: "Điều bạn thích ở môn học (chọn nhiều)",
        feedbackNotePrompt: "Góp ý thêm (không bắt buộc)",
        feedbackNotePlaceholder: "Điều gì có thể giúp môn học tốt hơn?",
        feedbackSubmit: "Gửi đánh giá",
        feedbackHint: "Cần chấm sao & chọn độ khó để tiếp tục",
        feedbackNeedFieldsToast: "Vui lòng chấm sao và chọn độ khó nhé",
        feedbackThanksToast: "🙏 Cảm ơn bạn đã đánh giá môn học!",
        feedbackDiffEasy: "Dễ 😌",
        feedbackDiffMedium: "Vừa 👍",
        feedbackDiffHard: "Khó 🔥",
        feedbackTagClear: "Nội dung dễ hiểu",
        feedbackTagUseful: "Bài tập hữu ích",
        feedbackTagVideo: "Video chất lượng",
        feedbackTagTeacher: "Giảng viên nhiệt tình",
        feedbackTagPath: "Lộ trình hợp lý",
        feedbackTagChallenge: "Nhiều thử thách",
        feedbackRating0: "Chưa chấm",
        feedbackRating1: "Rất tệ 😞",
        feedbackRating2: "Chưa tốt 😕",
        feedbackRating3: "Bình thường 🙂",
        feedbackRating4: "Tốt 😃",
        feedbackRating5: "Tuyệt vời 🤩",
        starAlt: "XP",
        brainAlt: "Sức mạnh",
        backpackAlt: "Trang bị",
        refreshAlt: "Đổi nhân vật",
        meatAlt: "Độ no",
        chickAlt: "Thú cưng",
        bulbAlt: "Gợi ý",
        giftAlt: "Rương",
        partyAlt: "Phần thưởng",
        toastPickChar: "🎉 Đã chọn nhân vật! Bắt đầu hành trình nào!",
        toastBuyPrefix: "✅ Đã mua ",
        toastBuyOutfitSuffix: " · đã mặc",
        toastWearPrefix: "👕 Đã mặc ",
        toastOwnedBagPrefix: "🎒 ",
        toastOwnedBagSuffix: " đã có trong túi",
        toastNotEnoughPrefix: "💰 Chưa đủ XP để mua ",
        toastUnequip: "↩️ Đã tháo trang sức",
        toastSlotsFull: "⚠️ Đã đủ 6 ô trang bị",
        toastEquipGear: "✨ Đã đeo trang sức!",
        toastGearLocked: "🔒 Chưa sở hữu · mở rương hoặc mua ở Cửa hàng",
        toastSlotEmpty: "👉 Chạm trang sức bên dưới để đeo vào ô",
        toastAdopt: "🐣 Đã nhận nuôi thú cưng!",
        toastFeedNeed: "💰 Cần 50 XP để cho ăn",
        toastPetLevel: "⭐ Pet lên cấp!",
        toastFeedOk: "🍖 Pet no bụng hơn +25",
    },
    portfolio: {
        projectsTitle: "Dự án & sản phẩm",
        skillsTitle: "Kỹ năng đạt được",
        commentsTitle: "Nhận xét từ giảng viên",
        publicOn: "🌐 Công khai",
        publicOff: "🔒 Riêng tư",
        projectCountSuffix: "dự án",
        badgeCountSuffix: "huy hiệu",
        levelPrefix: "Level",
        screenshotPlaceholder: "screenshot",
        pctSuffix: "%",
        quoteOpen: '"',
        quoteClose: '"',
        metaSep: " · ",
        rocketAlt: "Dự án",
        medalAlt: "Huy hiệu",
        starAlt: "Level",
        linkAlt: "GitHub",
    },
    contests: {
        tabContest: "Cuộc thi",
        tabMission: "Nhiệm vụ",
        tabAchievement: "Thành tựu",
        statusOpen: "Đang mở",
        statusSoon: "Sắp diễn ra",
        statusEnded: "Đã kết thúc",
        btnJoin: "Tham gia",
        btnRemind: "Đặt nhắc",
        btnResults: "Xem kết quả",
        claimPrefix: "Nhận ",
        claimSuffix: " XP",
        xpSuffix: " XP",
        progressSep: "/",
        calendarAlt: "Ngày",
        usersAlt: "Người tham gia",
        trophyAlt: "Phần thưởng",
        toastJoinPrefix: "🏆 ",
        toastClaimPrefix: "⭐ +",
        toastClaimMid: " XP · ",
    },
    languagePractice: {
        tabEn: "🇬🇧 Tiếng Anh",
        tabJp: "🇯🇵 Tiếng Nhật",
        streakLabel: "ngày streak",
        xpLabel: "XP English",
        todayTitle: "Bài luyện hôm nay",
        dayDoneSep: "/",
        dayDoneSuffix: "xong",
        minSuffix: "p · +",
        xpUnit: "XP",
        btnDone: "✓ Hoàn thành",
        btnStart: "Bắt đầu →",
        dialogTitle: "Hội thoại với AI · Speaking",
        micHint: "Nhấn để nói — AI chấm phát âm & gợi ý sửa",
        skillsTitle: "Kỹ năng của bạn",
        wordsTitle: "Từ vựng hôm nay",
        wordsNewSuffix: "từ mới",
        pctSuffix: "%",
        flameAlt: "Streak",
        starAlt: "XP",
        languagesAlt: "Ngoại ngữ",
        targetAlt: "Bài luyện",
        clockAlt: "Thời lượng",
        chatAlt: "Hội thoại",
        micAlt: "Micro",
        trendAlt: "Kỹ năng",
        folderAlt: "Từ vựng",
        toastDone: "✓ Bạn đã hoàn thành bài này",
        toastStartPrefix: "🎧 Mở bài luyện: ",
        toastMic: "🎙️ Đang ghi âm… (stub)",
    },
    services: {
        searchPlaceholder: "Tìm thủ tục, dịch vụ…",
        searchAlt: "Tìm dịch vụ",
        createCta: "Tạo đơn",
        emptyTitle: "Không tìm thấy thủ tục phù hợp",
        myRequestsTitle: "Đơn của tôi",
        pendingSuffix: " chờ duyệt",
        approvedSuffix: " đã duyệt",
        rejectedSuffix: " từ chối",
        submittedPrefix: "Gửi ngày ",
        newBadge: "MỚI",
        statusPending: "Chờ duyệt",
        statusApproved: "Đã duyệt",
        statusRejected: "Từ chối",
        modalDateLabel: "Ngày / thời gian áp dụng",
        modalDatePlaceholder: "VD: 12/07/2026",
        modalReasonLabel: "Lý do / nội dung ",
        modalReasonRequired: "*",
        modalReasonPlaceholder: "Nhập lý do hoặc nội dung chi tiết cho đơn của bạn…",
        modalAttach: "Đính kèm minh chứng (bắt buộc)",
        modalCancel: "Hủy",
        modalSubmit: "Gửi đơn",
        closeAlt: "Đóng",
        fileAlt: "Đơn",
        hourglassAlt: "Chờ duyệt",
        checkAlt: "Đã duyệt",
        rejectAlt: "Từ chối",
        uploadAlt: "Đính kèm",
        arrowAlt: "Tạo đơn",
        toastSubmitPrefix: '✅ Đã gửi đơn "',
        toastSubmitSuffix: '" · chờ duyệt',
        featureComingSoon: "Tính năng đang phát triển. Vui lòng quay lại sau.",
        emptyRequests: "Bạn chưa có đơn nào.",
        errors: {
            reasonRequired: "Vui lòng nhập lý do / nội dung",
        },
        leave: {
            catalogName: "Xin nghỉ phép",
            catalogDesc: "Đăng ký nghỉ có phép kèm minh chứng",
            classLabel: "Lớp học",
            classPlaceholder: "Chọn lớp học",
            noClassHint: "Chưa có lớp học",
            dateLabel: "Ngày xin nghỉ",
            shiftLabel: "Ca / buổi học",
            shiftPlaceholder: "Chọn ca học",
            reasonLabel: "Lý do xin nghỉ",
            reasonPlaceholder: "Nhập lý do chi tiết (VD: em bị sốt cần đi khám bệnh viện)…",
            proofLabel: "Ảnh minh chứng",
            proofAttach: "Chọn ảnh minh chứng (JPEG, PNG, WEBP · tối đa 5MB)",
            proofPreviewAlt: "Xem trước minh chứng",
            viewOriginal: "Xem ảnh gốc",
            changeProof: "Đổi ảnh",
            uploading: "Đang tải ảnh…",
            submitting: "Đang gửi đơn…",
            emptyRequests: "Bạn chưa có đơn xin nghỉ phép nào.",
            detailTitle: "Chi tiết đơn xin nghỉ phép",
            detailClass: "Lớp học",
            reviewerNote: "Ghi chú người duyệt",
            reviewedAtPrefix: "Duyệt lúc ",
            uploadFailed: "Không thể tải ảnh minh chứng. Vui lòng thử lại.",
            submitFailed: "Không thể gửi đơn. Vui lòng thử lại.",
            invalidProofFile: "Chỉ chấp nhận ảnh JPEG, PNG hoặc WEBP, tối đa 5MB.",
            errors: {
                classRequired: "Vui lòng chọn lớp học",
                dateRequired: "Vui lòng chọn ngày nghỉ",
                shiftRequired: "Vui lòng chọn ca học",
                proofRequired: "Vui lòng tải ảnh minh chứng",
            },
        },
        application: {
            submitting: "Đang gửi đơn…",
            submitFailed: "Không thể gửi đơn. Vui lòng thử lại.",
            uploadFailed: "Không thể tải ảnh minh chứng. Vui lòng thử lại.",
            invalidProofFile: "Chỉ chấp nhận ảnh JPEG, PNG hoặc WEBP, tối đa 5MB.",
            proofLabel: "Ảnh minh chứng",
            proofOptional: " (tùy chọn)",
            proofAttach: "Chọn ảnh minh chứng (JPEG, PNG, WEBP · tối đa 5MB)",
            proofPreviewAlt: "Xem trước minh chứng",
            viewOriginal: "Xem file đính kèm",
            changeProof: "Đổi ảnh",
            uploading: "Đang tải ảnh…",
            detailTitle: "Chi tiết đơn đăng ký",
            detailCode: "Mã đơn",
            detailType: "Loại đơn",
            rejectReason: "Lý do từ chối",
            reviewedAtPrefix: "Duyệt lúc ",
            notesLabel: "Ghi chú",
            semesterLabel: "Học kỳ",
            semesterPlaceholder: "VD: Học kỳ 1 - Năm học 2026 - 2027",
            courseNameLabel: "Học phần",
            courseNamePlaceholder: "VD: CT313 - Cấu trúc dữ liệu và giải thuật",
            courseCodeLabel: "Mã học phần",
            courseCodePlaceholder: "VD: CT313",
            examTypeLabel: "Loại kỳ thi",
            examTypePlaceholder: "Chọn loại kỳ thi",
            examTypeRetake: "Thi lại",
            examTypeSupplementary: "Thi bổ sung",
            currentGradeLabel: "Điểm hiện tại",
            currentGradePlaceholder: "VD: 6.5",
            commitmentDateLabel: "Ngày cam kết nộp phí",
            fromSemesterLabel: "Từ học kỳ",
            toSemesterLabel: "Đến học kỳ",
            fromYearLabel: "Từ năm học",
            toYearLabel: "Đến năm học",
            semesterSelectPlaceholder: "Chọn học kỳ",
            yearSelectPlaceholder: "Chọn năm học",
            examDateLabel: "Ngày thi",
            examBatchLabel: "Đợt thi",
            examBatchPlaceholder: "Chọn đợt thi",
            examShiftLabel: "Ca thi",
            examShiftPlaceholder: "Chọn ca thi",
            examRoomLabel: "Phòng thi",
            examRoomPlaceholder: "VD: P.302-A2",
            types: {
                RE_EXAM: "Đăng ký thi lại / Thi bổ sung",
                RE_GRADE: "Đăng ký phúc khảo",
                RE_GRADE_DOC: "Đơn phúc khảo điểm",
                LEAVE_LONG_TERM: "Xin ngừng học có thời hạn",
                TUITION_DELAY: "Xin chậm nộp học phí",
                ACADEMIC_RESERVE: "Xin bảo lưu kết quả học tập",
                EXAM_POSTPONE: "Xin hoãn thi học phần",
                RE_LEARN: "Đăng ký học lại",
            },
            descs: {
                RE_EXAM: "Đăng ký thi lại môn nợ hoặc thi bổ sung do hoãn thi",
                RE_GRADE: "Đề nghị chấm lại / kiểm tra bài thi",
                RE_GRADE_DOC: "Phúc khảo điểm quá trình / bài tập / đồ án",
                LEAVE_LONG_TERM: "Xin nghỉ học tạm thời có thời hạn (1–2 học kỳ)",
                TUITION_DELAY: "Xin hoãn/chậm nộp học phí theo cam kết",
                ACADEMIC_RESERVE: "Bảo lưu kết quả các môn đã tích lũy",
                EXAM_POSTPONE: "Xin hoãn kỳ thi học phần vì lý do chính đáng",
                RE_LEARN: "Đăng ký học lại môn bị nợ hoặc cải thiện điểm",
            },
            errors: {
                courseNameRequired: "Vui lòng chọn học phần",
                examTypeRequired: "Vui lòng chọn loại kỳ thi",
                commitmentDateRequired: "Vui lòng chọn ngày cam kết",
                fromSemesterRequired: "Vui lòng chọn học kỳ bắt đầu",
                fromYearRequired: "Vui lòng chọn năm học bắt đầu",
                toSemesterRequired: "Vui lòng chọn học kỳ kết thúc",
                toYearRequired: "Vui lòng chọn năm học kết thúc",
                examDateRequired: "Vui lòng chọn ngày thi",
                currentGradeInvalid: "Điểm hiện tại không hợp lệ",
                proofRequired: "Vui lòng tải ảnh minh chứng",
            },
        },
    },
    chatbot: {
        sidebarTitle: "Hội thoại",
        newConversation: "Hội thoại mới",
        newConversationShort: "Mới",
        send: "Gửi",
        sendAlt: "Gửi câu hỏi",
        inputPlaceholder: "Nhập câu hỏi về quy trình…",
        untitledConversation: "Hội thoại mới",
        sourcesLabel: "Nguồn",
        labelSeparator: ": ",
        charCountSeparator: "/",
        emptyEyebrow: "Rika Support",
        emptyTitle: "Hỏi gì cũng được — trong phạm vi thủ tục",
        emptyBody: "Bot trả lời theo tài liệu nhà trường. Chọn một chủ đề phổ biến để bắt đầu:",
        emptyNoSelectionTitle: "Chọn hội thoại để tiếp tục",
        emptyNoSelectionBody: "Mở một hội thoại bên trái, hoặc tạo mới để hỏi thủ tục khác.",
        emptySidebarHint: "Chưa có hội thoại",
        emptySidebarHintBody: "Bắt đầu bằng câu hỏi mẫu hoặc nút tạo mới.",
        suggestCta: "Hỏi ngay",
        contactHeading: "Đầu mối liên hệ",
        contactDepartmentLabel: "Bộ phận",
        contactEmailLabel: "Email",
        contactPhoneLabel: "Điện thoại",
        typingLabel: "Đang trả lời",
        assistantAvatarAlt: "Trợ lý",
        widgetOpenAlt: "Mở Rika Support",
        widgetCloseAlt: "Đóng Rika Support",
        widgetPanelTitle: "Rika Support",
        widgetPanelSubtitle: "Hỏi thủ tục theo tài liệu nhà trường",
        suggested: {
            leaveOfAbsence: "Em muốn xin nghỉ học tạm thời thì làm thủ tục thế nào?",
            scholarship: "Điều kiện xét học bổng như thế nào?",
            tuition: "Em cần hỏi về thủ tục học phí / bảo lưu.",
        },
        suggestedTitles: {
            leaveOfAbsence: "Xin nghỉ học",
            scholarship: "Học bổng",
            tuition: "Học phí & bảo lưu",
        },
        errors: {
            contentRequired: "Vui lòng nhập câu hỏi",
            contentTooLong: "Câu hỏi tối đa 2000 ký tự",
            assistantBusy: "Trợ lý đang bận, vui lòng thử lại",
            sendFailed: "Không gửi được câu hỏi. Vui lòng thử lại.",
            notFound: "Không tìm thấy hội thoại",
            loadFailed: "Không tải được hội thoại. Vui lòng thử lại.",
            createFailed: "Không tạo được hội thoại. Vui lòng thử lại.",
        },
    },
    quizSession: {
        startedToast: "Bài kiểm tra đang diễn ra — Bấm để tham gia",
        stoppedToast: "Giảng viên đã kết thúc phiên kiểm tra",
        submitSuccess: "Nộp bài thành công",
        timeUp: "Hết thời gian — Bài làm đã được nộp tự động",
        alreadySubmitted: "Bạn đã nộp bài cho phiên này",
        closed: "Phiên kiểm tra đã đóng hoặc chưa được mở",
        notInClass: "Bạn không thuộc lớp của phiên kiểm tra",
        loadError: "Không tải được bài kiểm tra. Vui lòng thử lại.",
        emptyList: "Chưa có bộ đề Quiz cho buổi học này.",
        teacherWillStart: "Giáo viên sẽ mở phiên kiểm tra trong buổi học.",
        notStartedToast: "Phiên làm bài chưa bắt đầu",
        statusStarted: "Đã bắt đầu",
        statusNotStarted: "Chưa bắt đầu",
        closedTitle: "Phiên kiểm tra đã kết thúc",
        closedBody: "Giảng viên đã đóng phiên. Nếu bạn đã nộp bài, điểm sẽ hiển thị khi có kết quả.",
        backToList: "Quay lại danh sách",
        durationLabel: "Thời lượng",
        durationSuffix: "phút",
        questionCountLabel: "Số câu",
        passThresholdLabel: "Ngưỡng đạt",
        percentSuffix: "%",
        progressLabel: "Đã trả lời {answered}/{total} câu",
        submitCta: "Nộp bài",
        submitting: "Đang nộp bài...",
        resultTitle: "Kết quả bài kiểm tra",
        scoreLabel: "Điểm",
        scoreMaxSuffix: "/10",
        correctLabel: "Số câu đúng",
        submittedAtLabel: "Thời gian nộp",
        waitingTitle: "Chờ giáo viên mở bài",
        listCta: "Mở đề",
        examLocked: "Phiên làm bài đã kết thúc",
        textQuestionHint: "Câu này không chọn đáp án trên giao diện.",
        optionAria: "Chọn đáp án {key}",
    },
    schedule: {
        weekTitle: "Lịch học tuần này",
        emptyDay: "Nghỉ",
        upcomingTitle: "Sự kiện sắp tới",
        prevWeekAlt: "Tuần trước",
        nextWeekAlt: "Tuần sau",
        calendarAlt: "Lịch",
        clockAlt: "Giờ",
        pinAlt: "Phòng",
        toastWeekStub: "📅 Chuyển tuần (stub)",
        toastClassPrefix: "📚 ",
        toastClassSep: " · ",
        typeStudy: "Lịch học",
        typeExam: "Lịch thi",
        typeDeadline: "Hạn nộp bài",
        typePrep: "Chuẩn bị bài",
    },
    dev: {
        api: {
            notAvailable: "Not available",
            missingStudentId: "Thiếu studentId",
            missingAdminBasicAuth: "Thiếu DEV_ADMIN_BASIC_USER / DEV_ADMIN_BASIC_PASS trong .env.local",
            missingLmsApiUrl: "Thiếu LMS_API_URL",
            missingLessonOrStudentId: "Thiếu lessonId hoặc studentId",
            missingSessionOrStudentId: "Thiếu sessionId hoặc studentId",
        },
    },
    components: {
        editor: {
            mermaid: {
                title: "Mermaid",
                preview: "Xem trước",
                editCode: "Sửa mã",
                previewTitle: "Xem trước",
                editSource: "Sửa nguồn",
                copyCode: "Sao chép mã",
                editorModeHint: "Chỉnh sửa mã Mermaid bên dưới",
                syntaxError: "Lỗi cú pháp",
                fixErrorButton: "Sửa lỗi",
                emptyChart: "Biểu đồ trống",
                startWriting: "Bắt đầu viết mã Mermaid",
            },
        },
    },
    studentServices: {
        selectMethodHint: "Vui lòng chọn hình thức bạn muốn thực hiện",
        fillOnlineTitle: "Điền form trực tuyến",
        fillOnlineBadge: "Trực tiếp trên Web",
        fillOnlineDesc: "Nhập các thông tin cần thiết trực tiếp theo biểu mẫu có sẵn trên hệ thống.",
        uploadFileTitle: "Nộp file mẫu đơn",
        uploadFileBadge: "Đính kèm File mẫu",
        uploadFileDesc: "Tải mẫu đơn về điền, ký tên và đính kèm file đã hoàn thành (PDF/Word/Ảnh) lên hệ thống.",
        downloadTemplateBtn: "Tải mẫu loại đơn",
        downloadTemplateTitle: "Tải mẫu đơn đăng ký",
        downloadTemplateDesc: "Chọn và tải về biểu mẫu phù hợp để điền thông tin trước khi gửi yêu cầu.",
        searchTemplatePlaceholder: "Tìm kiếm mẫu đơn theo tên...",
        downloadFileBtn: "Tải về",
        submitCompletedFileTitle: "Nộp file mẫu đơn đã hoàn thành",
        uploadFileNotesLabel: "Ghi chú thêm (nếu có)",
        clickToSelectFile: "Bấm vào đây để chọn file đơn",
        fileFormatHint: "Hỗ trợ các file .pdf, .doc, .docx, .png, .jpg (Tối đa 10MB)",
        completedFileLabel: "File mẫu đơn đã hoàn thành",
        downloadTemplate: "Tải mẫu về",
        clearDate: "Xóa ngày",
        allFilter: "Tất cả",
        attachedFile: "File đính kèm",
        submittingFile: "Đang nộp...",
        submitFile: "Gửi đơn file",
        infoTitle: "Thông tin",
        reExamInfoText1: "Dành cho sinh viên đăng ký tham gia kỳ thi lại hoặc kỳ thi bổ sung theo quy định đào tạo của Nhà trường.",
        reExamFeeNotice:
            "Sinh viên vui lòng thanh toán lệ phí 300.000đ cho mỗi lần thi lại/thi bổ sung và đính kèm hóa đơn thanh toán để hoàn tất hồ sơ. Nhà trường sẽ chỉ tiếp nhận và xử lý hồ sơ sau khi xác nhận thanh toán.",
        selectCoursePlaceholder: "-- Chọn học phần --",
        fromLabel: "Từ:",
        toLabel: "Đến:",
        noMatchingRequests: "Không tìm thấy đơn phù hợp với bộ lọc.",
        kbUnit: "KB",
    },
} as const;
