name: CI

on:
    pull_request:
        branches: ["main", "develop"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v5

            - name: Install pnpm
              uses: pnpm/action-setup@v4

            - name: Use Node.js
              uses: actions/setup-node@v5
              with:
                  node-version: "20"
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Lint
              run: pnpm run lint

            - name: Build
              run: pnpm run build
              env:
                  NEXT_PUBLIC_GA_MEASUREMENT_ID: ${{ secrets.NEXT_PUBLIC_GA_MEASUREMENT_ID }}
